[workspace]
   resolver = "2"
   members = [
      "lib",
      "api_bdkwallet",
      "cli_bdkwallet",
      "egui_bdkwallet",
      "egui_helloworld",
      "egui_mobileresponsive",
      "egui_advancedwallet"
]
