[package]
name = "cli_btcwallet"
version = "0.1.0"
edition = "2021"

# See more keys: and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bdk = { version = "0.29.0", features = ["keys-bip39"] }

[dev-dependencies]
anyhow = "1"
httpc-test = "0.1.1"
